#!/bin/bash
##################################################################################
#
# MCU-Juaad Board's Repository Cloning Script
#
###############################################
# Copyright (C) 2006-2020 Abhijit Bose <https://boseji.com>. All right reserved.
#
# This program is free software; you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the 
# Free Software Foundation; version 2.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. 
#
# SPDX-License-Identifier: GPL-2.0-only
# https://spdx.org/licenses/GPL-2.0-only.html
#
##################################################################################
echo
echo "  MCU-Juaad Board's Repository Cloning Script"
echo "-----------------------------------------------"
echo
# Variables
USER="arduino"
REPO="ArduinoCore-samd"
BUILD_DIR="build"
REPO_DIR="samd"
# Find the Latest Tag
TAG=`curl -s https://api.github.com/repos/$USER/$REPO/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'`

echo
echo "  Clonning into $REPO Latest Tag: $TAG ..."
echo

# Create the build Directory
if [[ -d "${BUILD_DIR}" ]] ; then
    rm -rf $BUILD_DIR
fi
mkdir $BUILD_DIR
cd $BUILD_DIR

# Perfrom the Actual Cloning
git clone -b $TAG --depth 1 https://github.com/$USER/$REPO.git $REPO_DIR
# Remove Git
rm -rf $REPO_DIR/.git $REPO_DIR/variants 
rm $REPO_DIR/*.* &>/dev/null
rm $REPO_DIR/* &>/dev/null
rm $REPO_DIR/.* &>/dev/null
mv $REPO_DIR/bootloaders/zero $REPO_DIR/zero-boot
rm -rf $REPO_DIR/bootloaders
mkdir -p $REPO_DIR/bootloaders
mv $REPO_DIR/zero-boot $REPO_DIR/bootloaders/zero
# Remove Other Things

# Restore
cd ..

echo
echo "  Success !"
echo
